const API="https://3dtomb.space/api/search";
const searchForm=document.getElementById("searchForm"),searchInput=document.getElementById("searchInput"),results=document.getElementById("results"),statusElement=document.getElementById("status"),countElement=document.getElementById("count"),refreshButton=document.getElementById("refreshButton"),viewerPanel=document.getElementById("viewerPanel"),closeViewer=document.getElementById("closeViewer"),modelViewer=document.getElementById("modelViewer"),viewerTitle=document.getElementById("viewerTitle"),viewerName=document.getElementById("viewerName"),viewerMeta=document.getElementById("viewerMeta"),arButton=document.getElementById("arButton"),licenseText=document.getElementById("licenseText");
let lastQuery="car",currentResults=[];
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function isUsdz(i){return String(i.format||"").toLowerCase()==="usdz"||String(i.fileUrl||"").toLowerCase().includes(".usdz")}
function isCompatible(i){const f=String(i.format||"").toLowerCase();return f==="glb"||f==="usdz"||Boolean(i.glbUrl)}
function thumb(i){return i.thumbnail||"https://placehold.co/800x800/17171d/ffffff?text=3D"}
function loading(){results.innerHTML='<div class="empty"><div class="spinner"></div>Searching the vault...</div>';statusElement.textContent="Searching";countElement.textContent=""}
async function searchModels(q){lastQuery=q.trim()||"car";loading();try{const p=new URLSearchParams({q:lastQuery,sort:"likes",limit:"48",offset:"0"});const r=await fetch(`${API}?${p}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();const a=Array.isArray(d)?d:(d.items||d.results||d.models||[]);currentResults=a.filter(isCompatible);render(currentResults)}catch(e){console.error(e);results.innerHTML=`<div class="empty">Could not reach the model vault.<br><br>${escapeHtml(e.message)}</div>`;statusElement.textContent="Connection error";countElement.textContent=""}}
function render(items){if(!items.length){results.innerHTML='<div class="empty">No compatible models found. Try another search.</div>';statusElement.textContent="No results";return}results.innerHTML=items.map((i,n)=>`<article class="card"><img class="thumb" src="${escapeHtml(thumb(i))}" alt="${escapeHtml(i.name)}" loading="lazy"><div class="cardBody"><div class="cardTitle">${escapeHtml(i.name)}</div><div class="cardMeta"><span>${escapeHtml(i.author||i.source||"Unknown")}</span><span>${escapeHtml(String(i.format||"3D").toUpperCase())}</span></div><div class="cardActions"><button class="previewButton" data-index="${n}">Preview</button>${isUsdz(i)?`<button class="arMini" data-ar-index="${n}">AR</button>`:""}</div></div></article>`).join("");statusElement.textContent="Ready";countElement.textContent=`${items.length} results`}
function openViewer(i){const glb=i.glbUrl||(String(i.format||"").toLowerCase()==="glb"?i.fileUrl:"");const u=isUsdz(i)?i.fileUrl:"";viewerTitle.textContent=i.name||"Object";viewerName.textContent=i.name||"Object";viewerMeta.textContent=`${i.author||i.source||"Unknown"} · ${String(i.format||"3D").toUpperCase()}`;licenseText.textContent=`License: ${i.license||"Check the source license before reuse."}`;modelViewer.removeAttribute("src");modelViewer.removeAttribute("ios-src");if(glb)modelViewer.src=glb;if(u)modelViewer.setAttribute("ios-src",u);arButton.hidden=!u;if(u)arButton.href=u;viewerPanel.classList.remove("hidden")}
function closePanel(){viewerPanel.classList.add("hidden");modelViewer.removeAttribute("src");modelViewer.removeAttribute("ios-src")}
searchForm.addEventListener("submit",e=>{e.preventDefault();searchModels(searchInput.value)});document.querySelectorAll(".chip").forEach(b=>b.addEventListener("click",()=>{searchInput.value=b.dataset.query;searchModels(b.dataset.query)}));results.addEventListener("click",e=>{const p=e.target.closest("[data-index]"),a=e.target.closest("[data-ar-index]");if(p)openViewer(currentResults[+p.dataset.index]);if(a){const i=currentResults[+a.dataset.arIndex];if(isUsdz(i)){arButton.href=i.fileUrl;arButton.click()}}});closeViewer.addEventListener("click",closePanel);refreshButton.addEventListener("click",()=>searchModels(lastQuery));searchModels(lastQuery);
